### PR TITLE
Add landing page and pin requirements versions

### PR DESCRIPTION
**Pull request by jnsgruk**
A trivial update that:

- Adds a nice landing page (similar to the Hello, Kubecon! charm)
- Pins the versions in `requirements.txt` to try and make this last
- Include `psycopg2-binary` as a requirement.

### CODE REVIEW

**Comment by jnsgruk** [comment]
Ideally merge along with https://github.com/juju/hello-juju-charm/pull/2

**Comment by jnsgruk** [comment]
Ideally merge along with https://github.com/juju/hello-juju-charm/pull/2

**Review by benhoyt — APPROVED** [review]
LGTM!

**Comment by jnsgruk** [comment]
@jameinel are you able to merge this?

**Pull request merged**
